apiVersion: v2
name: microservices
description: A Helm chart for microservices e-commerce application
type: application
version: 1.0.0
appVersion: "1.0"
keywords:
  - microservices
  - e-commerce
  - gke
maintainers:
  - name: DevOps

dependencies:
  - name: redis
    version: 25.2.0
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled